import { loadMermaid, renderMermaid } from "./mermaidLoader.js";
import { parseConfluence } from "./confluenceParser.js";
import { exportAsPdf, exportAsHtml, exportAsWiki } from "./exportService.js";

const fileInput = document.getElementById("fileInput");
const uploadBtn = document.getElementById("uploadBtn");
const sampleBtn = document.getElementById("sampleBtn");
const preview = document.getElementById("preview");
const raw = document.getElementById("rawMarkdown");
const toggleRaw = document.getElementById("toggleRaw");
const versionSelect = document.getElementById("mermaidVersion");
const dropZone = document.getElementById("dropZone");
const themeToggle = document.getElementById("themeToggle");
const downloadPdfBtn = document.getElementById("downloadPdfBtn");
const exportHtmlBtn = document.getElementById("exportHtmlBtn");
const saveWikiBtn = document.getElementById("saveWikiBtn");
const processingIndicator = document.getElementById("processingIndicator");
const processingText = document.getElementById("processingText");

// ---------------------------------------------------------------------------
// Sample / demo content
// ---------------------------------------------------------------------------

const SAMPLE_WIKI = `h1. Vonfluence Feature Demo

This page demonstrates every major Confluence wiki syntax feature supported by Vonfluence.

h2. Inline Formatting

This paragraph shows *bold text*, _italic text_, {{monospace code}}, ^superscript^, ~subscript~, and -strikethrough- text.

Here is a named link: [Confluence Docs|https://confluence.atlassian.com] and a bare URL: [https://example.com].

Line break works here: \\\\continues on the same visual block.

{color:red}Red text{color} and {color:#0052cc}blue text{color} via the color macro.

----

h2. Panels

{info}
*Info panel* — use for general information. Supports _inline formatting_ too.
{info}

{tip}
*Tip panel* — use for helpful hints and best practices.
{tip}

{warning}
*Warning panel* — use for potentially risky actions.
{warning}

{note}
*Note panel* — use for important reminders.
{note}

{panel:title=Custom Panel Title}
A *panel* macro with a custom title. Great for callouts that don't fit the standard types.
{panel}

{quote}
"The best documentation is the one that doesn't need to exist."
— Every Developer Ever
{quote}

----

h2. Lists

Unordered list with nesting:

* Alpha
* Beta
** Beta-1
** Beta-2
*** Beta-2-a
* Gamma

Ordered list with nesting:

# First step
# Second step
## Sub-step A
## Sub-step B
# Third step

----

h2. Table

||Name||Role||Department||Status||
|Alice|Lead Engineer|Platform|Active|
|Bob|UX Designer|Product|Active|
|Carol|Engineering Manager|Platform|On Leave|
|Dave|QA Engineer|Quality|Active|

----

h2. Code Blocks

{code:language=javascript}
// Fibonacci sequence — iterative
function fibonacci(n) {
    let a = 0, b = 1;
    for (let i = 0; i < n; i++) {
        [a, b] = [b, a + b];
    }
    return a;
}

console.log(fibonacci(10)); // 55
{code}

{noformat}
Plain preformatted text — spaces and
  indentation are   preserved exactly.
{noformat}

----

h2. Mermaid Diagram

{mermaid}
graph TD
    A[Paste / Upload Wiki] --> B[confluenceParser.js]
    B --> C{Block macros?}
    C -->|Yes| D[Extract to placeholders]
    C -->|No| E[Process lines]
    D --> E
    E --> F[Inline formatting]
    F --> G[Reinsert blocks]
    G --> H[DOMPurify.sanitize]
    H --> I[preview innerHTML]
    I --> J[mermaidLoader.js]
    J --> K[SVG Diagrams]
{/mermaid}

----

h2. Sequence Diagram

{mermaid}
sequenceDiagram
    participant U as User
    participant A as app.js
    participant P as confluenceParser
    participant M as mermaidLoader

    U->>A: paste / upload wiki text
    A->>P: parseConfluence(text)
    P-->>A: raw HTML
    A->>A: DOMPurify.sanitize
    A->>A: preview.innerHTML = html
    A->>M: renderMermaid(preview)
    M-->>A: SVGs injected
    A-->>U: page rendered
{/mermaid}

----

h6. Generated by Vonfluence`;


let renderSeq = 0;
let inputDebounce = null;
let processSeq = 0;
const activeProcesses = new Map();
const PROCESSING_DELAY_MS = 120;

// ---------------------------------------------------------------------------
// Upload / drag-drop
// ---------------------------------------------------------------------------

uploadBtn.onclick = () => fileInput.click();

fileInput.onchange = async e => {
    const file = e.target.files[0];
    if (file) {
        await readFile(file, uploadBtn);
    }
    e.target.value = "";
};

dropZone.addEventListener("dragover", e => {
    e.preventDefault();
    dropZone.classList.add("dragover");
});

dropZone.addEventListener("dragleave", () => {
    dropZone.classList.remove("dragover");
});

dropZone.addEventListener("drop", async e => {
    e.preventDefault();
    dropZone.classList.remove("dragover");
    const file = e.dataTransfer.files[0];
    if (file) {
        await readFile(file);
    }
});

// ---------------------------------------------------------------------------
// Processing indicator
// ---------------------------------------------------------------------------

function refreshProcessingIndicator() {
    const visible = Array.from(activeProcesses.values()).filter(job => job.visible);

    if (visible.length === 0) {
        processingIndicator.classList.add("hidden");
        processingIndicator.setAttribute("aria-hidden", "true");
        return;
    }

    const latest = visible[visible.length - 1];
    processingText.textContent = latest.message;
    processingIndicator.classList.remove("hidden");
    processingIndicator.setAttribute("aria-hidden", "false");
}

function startProcessing(message) {
    const id = ++processSeq;
    const job = {
        message: message || "Processing...",
        visible: false,
        timer: null
    };

    job.timer = setTimeout(() => {
        const active = activeProcesses.get(id);
        if (!active) return;
        active.visible = true;
        refreshProcessingIndicator();
    }, PROCESSING_DELAY_MS);

    activeProcesses.set(id, job);
    refreshProcessingIndicator();
    return id;
}

function stopProcessing(id) {
    const job = activeProcesses.get(id);
    if (!job) return;
    clearTimeout(job.timer);
    activeProcesses.delete(id);
    refreshProcessingIndicator();
}

function startControlLoading(control, loadingLabel) {
    if (!control) {
        return () => {};
    }

    const wasDisabled = control.disabled;
    const isButton = control.tagName === "BUTTON";
    const previousText = isButton ? control.textContent : "";

    control.disabled = true;
    control.classList.add("loading-control");

    if (isButton && loadingLabel) {
        control.textContent = loadingLabel;
    }

    return () => {
        control.disabled = wasDisabled;
        control.classList.remove("loading-control");

        if (isButton && loadingLabel) {
            control.textContent = previousText;
        }
    };
}

async function withProcessing(message, task, options = {}) {
    const { control = null, controlLabel = "", showIndicator = true } = options;
    const processId = showIndicator ? startProcessing(message) : null;
    const restoreControl = startControlLoading(control, controlLabel);

    try {
        return await task();
    } finally {
        restoreControl();
        if (processId !== null) {
            stopProcessing(processId);
        }
    }
}

// ---------------------------------------------------------------------------
// File reading
// ---------------------------------------------------------------------------

function readWikiFile(file) {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();

        reader.onload = e => {
            resolve(String(e.target?.result || ""));
        };

        reader.onerror = () => {
            reject(reader.error || new Error(`Failed to read "${file.name}"`));
        };

        reader.readAsText(file);
    });
}

async function readFile(file, control = null) {
    try {
        const wikiText = await withProcessing(`Reading ${file.name}...`, () => readWikiFile(file), {
            control,
            controlLabel: control ? "Loading..." : ""
        });

        raw.value = wikiText;
        await renderWiki(wikiText, "Rendering Confluence wiki + Mermaid...");
    } catch (error) {
        console.error(error);
        alert(`Failed to read file: ${file.name}`);
    }
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

async function renderWiki(wikiText, processingMessage = "Rendering...", useLoader = true) {
    const run = async () => {
        const seq = ++renderSeq;

        const rawHtml = parseConfluence(wikiText || "");
        const html = DOMPurify.sanitize(rawHtml, {
            ADD_ATTR: ["class", "style", "target", "rel"],
            ADD_TAGS: ["blockquote"]
        });

        preview.innerHTML = html;

        await loadMermaid(versionSelect.value);

        if (seq !== renderSeq) {
            return;
        }

        await renderMermaid(preview);
    };

    if (!useLoader) {
        await run();
        return;
    }

    await withProcessing(processingMessage, run);
}

// ---------------------------------------------------------------------------
// Controls
// ---------------------------------------------------------------------------

toggleRaw.onclick = () => {
    raw.classList.toggle("hidden");
};

raw.addEventListener("input", () => {
    clearTimeout(inputDebounce);
    inputDebounce = setTimeout(() => {
        renderWiki(raw.value).catch(error => {
            console.error(error);
        });
    }, 120);
});

versionSelect.onchange = async () => {
    try {
        await withProcessing(`Applying Mermaid ${versionSelect.value}...`, async () => {
            await renderWiki(raw.value, "", false);
        }, {
            control: versionSelect
        });
    } catch (error) {
        console.error(error);
        alert("Failed to switch Mermaid version.");
    }
};

themeToggle.onclick = () => {
    const theme = document.body.getAttribute("data-theme");
    document.body.setAttribute("data-theme", theme === "dark" ? "light" : "dark");
};

downloadPdfBtn.onclick = () => {
    exportAsPdf("Vonfluence Export");
};

exportHtmlBtn.onclick = () => {
    exportAsHtml(preview, "Vonfluence Export");
};

saveWikiBtn.onclick = () => {
    exportAsWiki(raw.value, "export");
};

sampleBtn.onclick = async () => {
    raw.value = SAMPLE_WIKI;
    await renderWiki(SAMPLE_WIKI, "Loading sample content...");
};

// ---------------------------------------------------------------------------
// Init
// ---------------------------------------------------------------------------

(async () => {
    try {
        await withProcessing(`Loading Mermaid ${versionSelect.value}...`, () => loadMermaid(versionSelect.value));
        if (raw.value.trim()) {
            await renderWiki(raw.value);
        } else {
            // Show sample content on first load so the page is never blank.
            raw.value = SAMPLE_WIKI;
            await renderWiki(SAMPLE_WIKI, "Rendering sample content...");
        }
    } catch (error) {
        console.error(error);
    }
})();
